name: Update Static Files

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-static:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.IDENTUS_CI }}
          fetch-depth: 0

      - name: Download github pages
        uses: ./.github/actions/get-pages
        with:
          github-token: ${{ secrets.IDENTUS_CI }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Update static files
        run: npm run report:regenerate

      - name: Update github pages
        uses: ./.github/actions/update-pages
        with:
          component: "static"
          gpg-private-key: ${{ secrets.HYP_BOT_GPG_PRIVATE }}
          gpg-passphrase: ${{ secrets.HYP_BOT_GPG_PASSWORD }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4